# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 512
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: UserBundle\Entity\User
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            http_basic: ~
            provider: main
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout


    role_hierarchy:
        ROLE_CLIENT:       ROLE_USER
        ROLE_BOT:       [ROLE_USER, ROLE_CLIENT]
        ROLE_ADMIN:       [ROLE_USER, ROLE_CLIENT, ROLE_BOT]

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
